### ISSUE TITLE
Wifi support for installing Elixir/Erlang?

### ISSUE THREAD

**Issue by chrismccord** [cromwellryan/sweetelixir#1]
@cromwellryan I'm assuming we'll have access to reliable wifi, otherwise we'll have major problems getting everyone setup. We could potentially clone the precompiled sources for Erlang at least to a flash drive, but all the build tools like homebrew, chocalately, etc won't be so easy.

**Comment by cromwellryan** [comment]
We should.  It's been good the last 3 years or so, but if we have time we can look into it.   A week or so before we should publish the prerequisite to the google group too.
