### ISSUE TITLE
Convert OTP GenServer to Tweet Aggregator

### ISSUE THREAD

**Issue by cromwellryan** [cromwellryan/sweetelixir#19]
This includes CustomClient, Supervisor/GenServer and adding a reporter.

**Comment by chrismccord** [comment]
We have distributed tweets! I have the base up and running with Client nodes that poll the twitter API and report messages back to an aggregator node. I also added a `GateKeeper` process that can run on a single node and "expose" the API credentials to remote clients. The GateKeeper will work well to teach simple process communication as well as let us allow all attendees to make API requests without having to distribute the API creds to everyone. 

Right now the Aggregator also serves as a reporter, but we have the core for presentation day and can enhance with reporters/stats servers as time allows. To get API creds, you'll have to create an app at https://dev.twitter.com/apps then click the "Create my access token" button at the bottom to generate all necessary creds. Give it a shot!

https://github.com/cromwellryan/sweetelixir/tree/master/10-otp/src/tweet_aggregator
