### ISSUE TITLE
Tweet Aggregator Leader setup needs windows support

### ISSUE THREAD

**Issue by cromwellryan** [cromwellryan/sweetelixir#20]
https://github.com/cromwellryan/sweetelixir/blob/master/04-setup/README.md

source .env won't work for windows.

replacing `export` with `set` and making this a .cmd or .bat _should_ work.

Low priority - I can work with those who need help day of.

**Comment by chrismccord** [comment]
Only the GateKeeper node ( you or me ) will need the env vars set so this shouldn't be an issue for attendees.

**Comment by cromwellryan** [comment]
Good point.
