### ISSUE TITLE
Does the layout work well?

### ISSUE THREAD

**Issue by cromwellryan** [cromwellryan/sweetelixir#6]
I'm second guessing the layout of the repo.  Reasons:
- It doesn't lend well to deep linking 
- Would be nice if going to [Basics](https://github.com/cromwellryan/sweetelixir/tree/master/07-basics) had a readme
- If we include source with a module, the source is a ../src away from the docs.  Not nice for the reader.

**Comment by chrismccord** [comment]
Docs living top level with a ./src folder would be good for me
